name: Build OpenWRT for mx4300 with NSS

on:
  push:
    branches:
      - 24.10-nss
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex g++ gawk \
            gcc-multilib gettext git libncurses-dev libssl-dev python3-distutils \
            rsync unzip zlib1g-dev file wget python3 python3-pip
          sudo pip3 install tqdm

      - name: Restore .config.default to .config
        run: cp .config.default .config

      - name: Download feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: |
          make defconfig
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-mx4300-nss
          path: bin/targets/**/openwrt-*.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/targets/**/openwrt-*.bin
