name: Custom OpenWRT Build & Release

on:
  push:
    branches:
      - 24.10-nss

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-setuptools zip unzip build-essential

      - name: Build OpenWRT
        run: |
          make defconfig
          make -j$(nproc)

      - name: Archive Source Directory
        run: |
          zip -r openwrt-source.zip . -x '*.git*' '*bin/*' '*staging_dir/*'

      - name: Upload Firmware Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-binaries
          path: bin/targets/**/*.bin

      - name: Upload Source Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-source
          path: openwrt-source.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_id }}
          name: OpenWRT Custom Build (Run ${{ github.run_number }})
          body: |
            ✅ 자동 생성된 커스텀 빌드입니다.
            - 빌드 번호: ${{ github.run_number }}
            - 시간: ${{ github.event.head_commit.timestamp }}
            - 태그: release-${{ github.run_id }}
          files: |
            bin/targets/**/*.bin
            openwrt-source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
