name: Build OpenWRT MX4300 NSS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev \
            libssl-dev python3-distutils python3-pyelftools qemu-utils rsync unzip wget \
            python3 python3-pip python3-setuptools python3-dev zlib1g-dev

      - name: Prepare .config
        run: |
          cp .config.default .config
          make defconfig

      - name: Download sources
        run: make download -j8

      - name: Compile firmware
        run: make -j$(nproc)

      - name: Upload firmware to release
        uses: ncipollo/release-action@v1
        with:
          tag: mx4300-nss-${{ github.run_number }}
          name: "MX4300 NSS Build #${{ github.run_number }}"
          body: |
            This is an automated MX4300 NSS build.
            Built from commit: ${{ github.sha }}
          artifacts: bin/targets/**/*-squashfs-sysupgrade.bin
