name: Build OpenWRT (mx4300 NSS)

on:
  push:
    branches:
      - 24.10-nss

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing tags & creating releases

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (for zip)
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget python3-pip

      - name: Prepare .config
        run: |
          cp .config.default .config
          make defconfig

      - name: Download sources
        run: make download -j$(nproc) || make download -j1 V=s

      - name: Build firmware
        run: make -j$(nproc) || make -j1 V=s

      - name: Organize output files
        run: |
          mkdir -p firmware_files
          mkdir -p source_files
          
          # Firmware binaries
          find bin/targets/ -type f \( -name '*.bin' \) -exec cp {} firmware_files/ \;

          # Source and metadata files
          find bin/targets/ -type f \( -name '*.config' -o -name '*.manifest' -o -name '*.buildinfo' -o -name '*.sha256sums' -o -name '*.packages' -o -name '*.feeds' \) -exec cp {} source_files/ \;

          # Create zip only for source files
          zip -r openwrt-source-files.zip source_files

      - name: Create tag
        id: tag
        run: |
          TAG_NAME="v24.10.nss.$(date +%Y%m%d)"
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: "OpenWRT NSS Build (${{ steps.tag.outputs.tag_name }})"
          body: |
            ✅ Auto-generated build from branch `24.10-nss`
            📅 Date: ${{ steps.tag.outputs.tag_name }}
            📦 Includes:
            - factory/sysupgrade firmware (.bin)
            - metadata/config/manifest (.config/.manifest/.sha256sums)
            - zipped sources
          files: |
            firmware_files/*.bin
            openwrt-source-files.zip
