name: Build OpenWRT NSS Firmware

on:
  push:
    branches:
      - 24.10-nss
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python3

      - name: Restore configuration
        run: |
          cp .config.default .config
          make defconfig

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build firmware
        run: make -j$(nproc)

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "OpenWRT NSS Build - ${{ github.run_number }}"
          tag_name: "autobuild-${{ github.run_number }}"
          files: bin/targets/**/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
