name: Build OpenWRT NSS & Release

on:
  workflow_dispatch:
  push:
    branches:
      - 24.10-nss

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build OpenWRT

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib git libncurses5-dev libssl-dev python3-distutils \
            rsync unzip zlib1g-dev file wget python3-setuptools

      - name: Setup OpenWRT feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load config
        run: |
          cp .config.default .config
          make defconfig

      - name: Start build
        run: |
          make -j$(nproc)

      - name: Prepare firmware zip
        run: |
          cd bin/targets/*/*
          zip -r openwrt-nss-firmware.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: OpenWRT NSS Build ${{ github.run_number }}
          tag_name: nss-r${{ github.run_number }}
          files: bin/targets/*/*/openwrt-nss-firmware.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
