name: OpenWrt NSS Build and Release

on:
  push:
    branches:
      - 24.10-nss

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev file wget python3-pyelftools

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            openwrt/tmp
            openwrt/staging_dir
            openwrt/build_dir
          key: ${{ runner.os }}-openwrt-nss-${{ hashFiles('**/.config') }}

      - name: Copy default config
        run: cp .config.default .config

      - name: Update & install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build OpenWrt (only image)
        run: make -j$(nproc) download world

      - name: Archive firmware files
        run: |
          mkdir -p release/firmware
          find bin/targets/ -type f -name '*.bin' -exec cp {} release/firmware/ \;
          find bin/targets/ -type f -name '*.img' -exec cp {} release/firmware/ \;

      - name: Archive source code as zip
        run: |
          zip -r release/source.zip . -x ".git/*" -x "bin/*" -x "build_dir/*" -x "staging_dir/*" -x "tmp/*"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-nss-${{ github.run_number }}
          name: NSS Build ${{ github.run_number }}
          body: |
            ✅ 자동 NSS 빌드 완료
            - `factory.bin`, `sysupgrade.bin`, 기타 이미지 파일
            - 소스코드 zip 파일 포함
          files: |
            release/firmware/*
            release/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
