name: Build OpenWRT for MX4300 NSS

on:
  push:
    branches:
      - 24.10-nss

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build MX4300 NSS Firmware

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            openwrt/tmp
            openwrt/dl
            openwrt/staging_dir
          key: ${{ runner.os }}-openwrt-${{ hashFiles('**/.config.default') }}

      - name: Prepare feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy default config
        run: |
          cp .config.default .config
          make defconfig

      - name: Build firmware
        run: |
          make -j$(nproc)

      - name: Upload firmware to artifact
        uses: actions/upload-artifact@v4
        with:
          name: mx4300-nss-firmware
          path: bin/targets/**/openwrt-*.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/')
        with:
          name: "Auto Build - ${{ github.sha }}"
          tag_name: "autobuild-${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/targets/**/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
